default:
  navigation:
    - title: PRODUITS
      subtitle: Categories
      url: /t/categories/produits
      items:
        - :title: CABLES
          :url: /t/categories/produits/cables
        - :title: COQUES POUR SMARTPHONES
          :url: /t/categories/produits/coque-pour-smartphones
        - :title: VERRES TREMPES
          :url: /t/categories/produits/verres-trempes
        - :title: COQUES POUR AIRPODS
          :url: /t/categories/produits/coques-pour-airpods
        - :title: AUTRES PRODUITS HIGH TECH
          :url: /t/categories/produits/autres-produits-high-tech
      promo_banners:
        - subtitle: New collection
          title:
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: CLIENT PROFESSIONELLE
      subtitle: Categories
      url: /t/client-professionelle
      items:
        - :title: CARTES DE VISITE VIP
          :url: /t/client-professionelle/cartes-de-visite-vip
        - :title: BLOC NOTE HIGH TECH
          :url: /t/client-professionelle/bloc-note-high-tech
        - :title: COQUES PERSONNALISEES
          :url: /t/client-professionelle/coques-personnalisees
        - :title: AUTRES PRODUITS HIGH TECH
          :url: /t/client-professionelle/autres-produits-high-tech

      promo_banners:
        - subtitle: New collection
          title:
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: PRODUITS PERSONNALISES
      subtitle: Categories
      url: /t/produits-personnalises
      items:
        - :title: VOTRE COQUE SMARTPHONE
          :url: /t/produits-personnalises/votre-coque-smartphone
        - :title: VOTRE COQUE AIRPOD
          :url: /t/produits-personnalises/votre-coque-airpod
        - :title: AUTRES PRODUITS PERSONNALISABLES
          :url: /t/produits-personnalises/autres-produits-personnalisables
      promo_banners:
        - subtitle: New collection
          title:
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
    - title: OFFRE PROMOTIONNELLE
      subtitle: Categories
      url: /t/offre-promotionnelle
      items:
        - :title: OFFRES SUR CABLES
          :url: /t/offre-promotionnelle/offres-sur-cables
        - :title: OFFRES SUR COQUE
          :url: /t/offre-promotionnelle/offres-sur-coque
        - :title: AUTRES OFFRES
          :url: /t/offre-promotionnelle/autres-offres
      promo_banners:
        - subtitle: New collection
          title:
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
